### ISSUE TITLE
Runscript method does not return a completed future

### ISSUE THREAD

**Issue by BillyYccc** [tsegismont/vertx-gsoc-2018-qotd#6]
When the execution is succeeded, the runScript method does not return a completed future.

The current code does nothing but like this:
https://github.com/tsegismont/vertx-gsoc-2018-qotd/blob/a7b2b7733ca10d80a6dde1e603cbda6cce98a31e/src/main/java/io/vertx/gsoc2018/qotd/QuoteOfTheDayVerticle.java#L41

It should be `future.complete();`

**Comment by tsegismont** [comment]
Fixed in #7
